version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: saveful_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saveful_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: saveful_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: saveful_meili
    restart: always
    environment:
      MEILI_MASTER_KEY: "meili_key_123"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  pgdata:
  redisdata:
  meili_data:
